# Desafio 3: Datamind.

Este desafio requer ao menos 15 descobertas sustentada por dados, quanto mais útil para a "empresa", melhor.

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Dataset_Data_Mining_Completo_5000.xlsx')

In [5]:
df.columns

Index(['ID_Compra', 'ID_Cliente', 'Idade', 'Sexo', 'Estado_Civil', 'Cidade',
       'Regiao', 'Renda_Mensal', 'Tempo_Cliente_Anos', 'Canal', 'Produto',
       'Categoria', 'Quantidade', 'Valor_Unitario', 'Desconto_%',
       'Valor_Total', 'Forma_Pagamento', 'Cupom', 'Programa_Fidelidade',
       'Avaliacao', 'Cancelou', 'Fraude', 'Mes', 'Data_Compra'],
      dtype='str')

In [14]:
# Quantidade de colunas no dataframe
df.columns.value_counts().sum()

np.int64(24)

In [46]:
df.head(5)

,ID_Compra,ID_Cliente,Idade,Sexo,Estado_Civil,Cidade,Regiao,Renda_Mensal,Tempo_Cliente_Anos,Canal,...,Desconto_%,Valor_Total,Forma_Pagamento,Cupom,Programa_Fidelidade,Avaliacao,Cancelou,Fraude,Mes,Data_Compra
0,1,C0122,38,F,Solteiro,Brasília,Centro-Oeste,20561,15,App,...,0,7200.0,Pix,Não,Sim,3,Não,Não,August,19/08/2025
1,2,C0012,70,M,Divorciado,Recife,Nordeste,8688,12,Loja,...,20,8960.0,Cartão,Sim,Sim,2,Sim,Sim,October,03/10/2025
2,3,C0300,36,M,Solteiro,Curitiba,Sul,2610,11,Site,...,0,1600.0,Pix,Não,Sim,4,Não,Não,August,06/08/2025
3,4,C0519,69,M,Casado,Curitiba,Sul,15561,15,Site,...,10,8100.0,Boleto,Sim,Não,5,Não,Não,December,10/12/2025
4,5,C0106,63,M,Casado,São Paulo,Sudeste,17597,7,App,...,10,10080.0,Boleto,Sim,Não,5,Não,Não,May,09/05/2025

Descoberta 01: Qual a relação entre gênero dos clientes?:

In [24]:
df['Sexo'].value_counts(normalize=True) * 100
# Pouco mais da metade dos clientes são do sexo feminino, 51,6% do total de clientes.

Sexo
F    51.6
M    48.4
Name: proportion, dtype: float64

In [25]:
# Totalizando:

df['Sexo'].value_counts()

Sexo
F    2580
M    2420
Name: count, dtype: int64

Descoberta 02: Qual a idade média dos clientes?:

Descoberta 03: Idade dos 100 clientes que mais dão faturamento para a empresa e suas rendas mensais:

In [75]:
df.sort_values('Valor_Total', ascending=False)[['Valor_Total','Renda_Mensal', 'Idade']].head(100)

      Valor_Total  Renda_Mensal  Idade
473       18000.0          7226     41
551       18000.0         10502     28
4228      18000.0         17968     38
4198      18000.0         21230     32
1944      18000.0          6449     23
...           ...           ...    ...
3583      15300.0         19506     21
3223      15300.0          4654     50
1578      15300.0          6455     33
3695      15300.0         10995     50
3618      15300.0          3705     64

[100 rows x 3 columns]

Descoberta 04: Quem são os 100 clientes com maior renda?

In [53]:
df['Renda_Mensal'].sort_values(ascending=False).head(100)

4674    21999
2272    21998
1765    21997
4849    21996
3155    21996
        ...
19      21715
3124    21715
3071    21712
956     21708
1829    21706
Name: Renda_Mensal, Length: 100, dtype: int64

Descoberta 05: Qual a relação entre clientes com maior renda e faturamento?

In [69]:
df.loc[df['Valor_Total'].idxmax(), ['Idade', 'Sexo', 'Renda_Mensal', 'Valor_Total']]

Idade                18
Sexo                  F
Renda_Mensal      21493
Valor_Total     18000.0
Name: 296, dtype: object

Descoberta 06: Qual a relação das compras fraudolentas com a idade, renda, valor total da compra e gênero dos clientes?:

In [ ]:
# Agrupa e ordena por Valor_Total dentro de cada grupo de Fraude
df.groupby('Fraude')[['Idade', 'Renda_Mensal', 'Sexo', 'Valor_Total']].apply(lambda g: g.sort_values('Valor_Total', ascending=True))

             Idade  Renda_Mensal Sexo  Valor_Total
Fraude
Não    3888     19         21773    F         96.0
       1294     69          8283    M         96.0
       206      48          8475    F         96.0
       167      70         13548    M         96.0
       4289     63          8517    M         96.0
...            ...           ...  ...          ...
Sim    3195     19         14267    F      17100.0
       3375     37          9647    F      18000.0
       2532     18          9083    F      18000.0
       2413     63          9882    M      18000.0
       1860     44         16047    F      18000.0

[5000 rows x 4 columns]

Quantas fraudes ocorreram e quais foram as datas?:

In [99]:
# Separando os datasets
fraudes = df[df['Fraude'] == 'Sim']
legitimas = df[df['Fraude'] == 'Não']

print("--- Comparativo Numérico (Fraude vs Legítima) ---")
print("Idade Média -> Fraude:", fraudes['Idade'].mean(), "| Legítima:", legitimas['Idade'].mean())
print("Renda Média -> Fraude:", fraudes['Renda_Mensal'].mean(), "| Legítima:", legitimas['Renda_Mensal'].mean())
print("Valor Total Médio -> Fraude:", fraudes['Valor_Total'].mean(), "| Legítima:", legitimas['Valor_Total'].mean())

print("\n--- Fraudes por Gênero ---")
print(fraudes['Sexo'].value_counts(normalize=True) * 100)

print("\n--- Fraudes por Mês ---")
print(fraudes['Mes'].value_counts())

--- Comparativo Numérico (Fraude vs Legítima) ---
Idade Média -> Fraude: 44.4125 | Legítima: 44.24166666666667
Renda Média -> Fraude: 12211.65 | Legítima: 12002.795325203251
Valor Total Médio -> Fraude: 11685.0125 | Legítima: 3083.159349593496

--- Fraudes por Gênero ---
Sexo
M    51.25
F    48.75
Name: proportion, dtype: float64

--- Fraudes por Mês ---
Mes
November     11
October       9
December      9
July          8
June          8
April         7
March         6
February      5
August        5
September     5
January       5
May           2
Name: count, dtype: int64

In [98]:
df.groupby('Estado_Civil') \
  .agg(Gasto_Medio=('Valor_Total', 'mean'), Itens=('Quantidade', 'mean'), Volume=('ID_Compra', 'count')) \
  .sort_values(by='Volume', ascending=False) \
  .round(2)

              Gasto_Medio  Itens  Volume
Estado_Civil
Casado            3149.90   2.53    1731
Solteiro          3192.62   2.47    1730
Divorciado        3332.19   2.51    1539