### Desafio de ciência de dados:

In [ ]:
import pandas as pd

Extraindo os dados para o data_frame

In [33]:
data_frame = pd.read_csv('vendas_loja_dataset.csv')

Visualizando colunas existentes e os últimos 5 registros do data_frame

In [55]:
data_frame.columns

Index(['VendaID', 'Data', 'Cliente', 'Cidade', 'Produto', 'Categoria',
       'Quantidade', 'Valor_Unitario', 'Valor_Total', 'Pagamento'],
      dtype='str')

In [56]:
data_frame.tail()

,VendaID,Data,Cliente,Cidade,Produto,Categoria,Quantidade,Valor_Unitario,Valor_Total,Pagamento
495,496,12/02/2026,Ana,Porto Velho,Headset,Informática,1,845.13,845.13,Pix
496,497,08/01/2026,Pedro,Rio Branco,Mouse,Informática,4,140.10,560.40,Cartão
497,498,04/04/2026,Bruno,Rio Branco,Monitor,Informática,2,1158.81,2317.62,Cartão
498,499,29/04/2026,João,Porto Velho,Monitor,Informática,1,726.04,726.04,Pix
499,500,12/01/2026,Bianca,Porto Velho,Notebook,Informática,4,4569.05,18276.20,Cartão

#### 1ª Pegunta

In [49]:
print('Cidade que mais fez vendas:', data_frame['Cidade'].max())

Cidade que mais fez vendas: Rio Branco

#### 2ª Pegunta

In [57]:
print('Produto que mais vendeu:', data_frame['Produto'].max())

Produto que mais vendeu: Teclado

#### 3ª Pegunta

In [58]:
print('Método de pagamento mais utilizado:', data_frame['Pagamento'].max())

Método de pagamento mais utilizado: Pix

#### 4ª Pegunta

In [60]:
print('Total faturado pela empresa: R$', data_frame['Valor_Total'].sum())

Total faturado pela empresa: R$ 1498016.55

#### 5ª Pegunta

In [ ]:
print('Dados da maior venda realizada:')
data_frame.loc[data_frame['Valor_Total'].idxmax(), ['VendaID', 'Produto', 'Cidade', 'Pagamento', 'Valor_Total', 'Quantidade']]

Dados da maior venda realizada:

VendaID            61
Produto         Mouse
Cidade          Belém
Pagamento      Boleto
Valor_Total     44.25
Quantidade          1
Name: 60, dtype: object

#### 6ª Pegunta

In [62]:
print('Dados da menor venda realizada:')
data_frame.loc[data_frame['Valor_Total'].idxmin(), ['VendaID', 'Produto', 'Cidade', 'Pagamento', 'Valor_Total']]

Dados da menor venda realizada:

VendaID            61
Produto         Mouse
Cidade          Belém
Pagamento      Boleto
Valor_Total     44.25
Name: 60, dtype: object

#### 7ª Pergunta

In [54]:
print('Quantidade de produtos únicos:', data_frame['Produto'].nunique())
print('Lista de produtos únicos:', data_frame['Produto'].unique())

Quantidade de produtos únicos: 7
Lista de produtos únicos: <StringArray>
['Monitor', 'Impressora', 'Teclado', 'Headset', 'Notebook', 'Mouse', 'SSD']
Length: 7, dtype: str

#### 8ª Pergunta

In [66]:
print('Categoria do produto que mais vendeu:')
data_frame.loc[data_frame['Valor_Total'].idxmax(), ['Categoria']]

Categoria do produto que mais vendeu:

Categoria    Informática
Name: 331, dtype: str

#### 9ª Pergunta

In [63]:
print('Cidade que mais gerou faturamento:')
data_frame.loc[data_frame['Valor_Total'].idxmax(), ['Valor_Total', 'Cidade']]

Cidade que mais gerou faturamento:

Valor_Total      25909.04
Cidade         Rio Branco
Name: 331, dtype: object

#### 10ª Pergunta

In [106]:
print('Produto mais vendido:')
data_frame.loc[(data_frame['Produto'] == data_frame['Produto'].value_counts().idxmax()) & (data_frame['Cidade'] == 'Boa Vista'), ['Produto', 'Quantidade']]

Produto mais vendido:

    Produto  Quantidade
12    Mouse           2
18    Mouse           2
34    Mouse           1
109   Mouse           3
149   Mouse           1
157   Mouse           1
159   Mouse           3
168   Mouse           1
197   Mouse           2
206   Mouse           2
217   Mouse           2
258   Mouse           1
266   Mouse           4
270   Mouse           3
308   Mouse           3
351   Mouse           1
367   Mouse           4
380   Mouse           3
383   Mouse           4
384   Mouse           2
417   Mouse           4
427   Mouse           2
480   Mouse           2

In [94]:
print('Clientes por cidade:')
data_frame.groupby('Valor_Total')['Cliente'].nunique().sort_values(ascending=False)

Clientes por cidade:

Valor_Total
560.40      2
48.93       1
11200.78    1
117.52      1
44.25       1
           ..
104.00      1
108.33      1
109.62      1
114.53      1
45.98       1
Name: Cliente, Length: 499, dtype: int64

In [109]:
print('Faturamento por cidade: R$')
data_frame.groupby('Cidade')['Valor_Total'].sum().sort_values(ascending=False)

Faturamento por cidade: R$

Cidade
Rio Branco     345796.40
Porto Velho    326262.95
Belém          282912.03
Manaus         276489.04
Boa Vista      266556.13
Name: Valor_Total, dtype: float64

In [135]:
print('Vendas por cidade: R$')
data_frame.groupby('Cidade')['VendaID'].count().sort_values(ascending=False)

Vendas por cidade: R$

Cidade
Belém          106
Rio Branco     103
Boa Vista       98
Porto Velho     97
Manaus          96
Name: VendaID, dtype: int64

In [134]:
print('Quantidade de produtos por cidade:')
data_frame.groupby(['Cidade'])['Produto'].value_counts().sort_values(ascending=True)

cidades = data_frame['Cidade'].unique()

for cidade in cidades:
    print(f'Quantidade de produtos vendidos na cidade {cidade}:')
    print(data_frame.loc[data_frame['Cidade'] == cidade].groupby('Produto')['Quantidade'].sum().sort_values(ascending=False))

Quantidade de produtos por cidade:
Quantidade de produtos vendidos na cidade Manaus:
Produto
Mouse         44
Teclado       40
SSD           36
Monitor       34
Headset       33
Impressora    27
Notebook      26
Name: Quantidade, dtype: int64
Quantidade de produtos vendidos na cidade Rio Branco:
Produto
Teclado       56
Monitor       52
Notebook      37
SSD           31
Mouse         29
Headset       27
Impressora    24
Name: Quantidade, dtype: int64
Quantidade de produtos vendidos na cidade Porto Velho:
Produto
Impressora    46
Teclado       42
Monitor       41
Notebook      37
SSD           32
Headset       20
Mouse         20
Name: Quantidade, dtype: int64
Quantidade de produtos vendidos na cidade Belém:
Produto
Headset       53
Mouse         42
SSD           40
Monitor       39
Impressora    38
Teclado       29
Notebook      27
Name: Quantidade, dtype: int64
Quantidade de produtos vendidos na cidade Boa Vista:
Produto
Mouse         53
Headset       37
Teclado       36
Monitor       34
Impressora    28
Notebook      25
SSD           16
Name: Quantidade, dtype: int64

In [ ]:
print('Valor de produtos por cidade:')
data_frame.groupby(['Cidade'])['Valor_Unitario'].value_counts().sort_values(ascending=True)

cidades = data_frame['Cidade'].unique()

for cidade in cidades:
    print(f'Quantidade de produtos vendidos na cidade {cidade}:')
    print(data_frame.loc[data_frame['Cidade'] == cidade].groupby('Produto')['Quantidade'].sum().sort_values(ascending=False))